spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:memory_db     # Memory DB
      username: ENC(gOoRKyXLG2p1whDGqXconA==)
      password: ENC(Ntv0UTntErHKYPzPrvJPWA==)

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create

kakao:
  auth:
    prefix: KakaoAK
    key:
      rest-api: ENC(lYhPqvyB2NKcLcMyAD7jEp4+U0FBg8wst2ikFRiM49NKUXRLbh0trFO48o+mXAJM)
  api:
    address:
      location: "https://dapi.kakao.com/v2/local/search/keyword.json?"