spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:data_store;
      username: chicken
      password: leg

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update