spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:mem:memory_db     # Memory DB
      jdbc-url: jdbc:h2:./data/local_db   # Local DB : 웹 콘솔 이외의 툴에서 사용하기 위해 임시로 셋팅 (config/ConfigH2Server 파일과 의존), 추 후 삭제 TODO: 최종 단계에서 삭제 필요
      username: chicken
      password: leg

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update

kakao:
  auth:
    prefix: KakaoAK
    key:
      rest-api: 4c643de95be12dc48aff7938967cc7e5
  api:
    address:
      location: "https://dapi.kakao.com/v2/local/search/keyword.json?"
